name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # TeamTalk unit test environment variables
  INPUTDEVICEID: 1978
  OUTPUTDEVICEID: 1978
  VIDEODEVICEID: None
  VERBOSE: 0
  GITHUBSKIP: 1

jobs:
  build:
    if: "!startsWith(github.head_ref, 'debug') || startsWith(github.head_ref, 'debug-linux')"
    permissions:
      contents: read
      security-events: write
      packages: read
      actions: write
    strategy:
      matrix:
        os: [ubuntu-24.04]
        include:
          - os: ubuntu-24.04
            version: "24"
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: true


    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: Update Ubuntu repository
      run: sudo apt-get update


    - name: Print env
      run: printenv | sort

    - name: Install dependencies
      working-directory: ${{github.workspace}}/Build
      run: sudo make depend-ubuntu${{ matrix.version }}

    - name: Build TeamTalk toolchain, libraries and apps
      working-directory: ${{github.workspace}}
      run: |
        source env.sh
        make CMAKE_EXTRA="-G Ninja -DFEATURE_WEBRTC=OFF -DBUILD_TEAMTALK_LIBRARY_UNITTEST_CATCH2=ON -DBUILD_TEAMTALK_LIBRARY_UNITTEST_CATCH2_PERF=OFF -DTOOLCHAIN_INSTALL_PREFIX=${{runner.workspace}}/toolchain-install -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install" -C Build ubuntu${{ matrix.version }}
        echo TEAMTALK_INSTALLDIR=${{runner.workspace}}/install>> $GITHUB_ENV


    - name: Build jSpamBot using Gradle
      working-directory: ${{github.workspace}}/Client/jSpamBot
      run: gradle build

    - name: Install TeamTalk SDK
      working-directory: ${{github.workspace}}/Build/build-release-ubuntu${{ matrix.version }}
      run: cmake --build . --target install

    - name: Copy test binary to install directory
      run: |
        cp ${{github.workspace}}/Build/build-release-ubuntu${{ matrix.version }}/Library/TeamTalkLib/test/catchtt ${{runner.workspace}}/install/

    - name: Build debug TeamTalk using prebuilt toolchain
      working-directory: ${{github.workspace}}
      run: |
        source env.sh
        make CONFIGTYPE=debug CMAKE_EXTRA="-DTOOLCHAIN_INSTALL_PREFIX=${{runner.workspace}}/toolchain-install -DTOOLCHAIN_BUILD_EXTERNALPROJECTS=OFF -DFEATURE_WEBRTC=OFF -DBUILD_TEAMTALK_LIBRARY_UNITTEST_CATCH2=ON -DBUILD_TEAMTALK_LIBRARY_UNITTEST_CATCH2_PERF=OFF -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install" -C Build ubuntu${{ matrix.version }}
        echo TEAMTALK_INSTALLDIR=${{runner.workspace}}/install>> $GITHUB_ENV

    - name: Upload TeamTalk SDK artifact
      uses: actions/upload-artifact@v7
      with:
        name: teamtalksdk-ubuntu${{ matrix.version }}
        path: ${{runner.workspace}}/install

    - name: Create Ubuntu ${{ matrix.version }} portable archives
      working-directory: ${{github.workspace}}
      run: |
        source env.sh
        cd Setup/Portable
        make ubuntu${{ matrix.version }} ubuntu${{ matrix.version }}pro

    - name: Upload TeamTalk portable artifact
      uses: actions/upload-artifact@v7
      with:
        name: teamtalk-ubuntu${{ matrix.version }}
        path: ${{github.workspace}}/Setup/Portable/teamtalk-*

    - name: Upload TeamTalk Pro artifact
      uses: actions/upload-artifact@v7
      with:
        name: teamtalkpro-ubuntu${{ matrix.version }}
        path: ${{github.workspace}}/Setup/Portable/teamtalkpro-*

